payment:
  key: sk_test_652cb496246c20a1a51456bdf96c12485b37cf7c
spring:
  data:
    mongodb:
      uri: mongodb+srv://jwsven:TjIfr1p3iJ9gQulK@jwsven.tik4weo.mongodb.net/mydatabase?retryWrites=true&w=majority
      database: event_db


  #    mongodb:
#      authentication-database: admin
#      username: admin
#      password: password
#      database: eventHub
#      host: localhost
#      port: 27017
#  application:
#    name: event-hub
  mail:
    host: smtp.gmail.com
    port: 587
    username: eventhubjava@gmail.com
    password: jtluggqffqginukh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expiration: 900000000

v1: 1
server:
  port: 8080

