#spring:
#  data:
#    mongodb:
#      authentication-database: admin
#      username: username
#      password: password
#      database: eventHub
#      host: localhost
#      port: 27017

jwt:
  expiration: 900000

server:
  port: 8999

