spring:
  data:
    mongodb:
      authentication-database: admin
      username: username
      password: password
      database: eventHub
      host: localhost
      port: 27017
  application:
    name: event-hub
  mail:
    host: smtp.gmail.com
    port: 587
    username: eventhubjava@gmail.com
    password: jtluggqffqginukh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expiration: 900000

server:
  port: 8999

