spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@eventhub.x3bwxlb.mongodb.net/eventhub?retryWrites=true&w=majority
  application:
    name: event-hub
  mail:
    host: smtp.gmail.com
    port: 587
    username: eventhubjava@gmail.com
    password: jtluggqffqginukh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  expiration:
    access-token: 86400000
    refresh-token: 259200000
v1: 1
server:
  port: 8999

